### PR TITLE
Add Docusaurus @site alias support

### PR DESCRIPTION
**Pull request by slorber**
We have a Webpack alias using `@site/*` relative to current site dir, so it make sense to add it by default to the TS config.

It seems that baseUrl is required for this to work, so used `.`, but my IDE can autocomplete imports without it so not sure it's really needed?

The problem is that now both imports work for TS:

```
import {xyz as xyz1} from '@site/src/testCode';
import {xyz as xyz2} from 'src/testCode';
```

However only the 1st will work in practice:

> Module not found: Error: Can't resolve 'src/testCode' in '/Users/sebastienlorber/Desktop/projects/docusaurus/website/src/pages'

Is there a way to enable just the first import?

I'm thinking about adding support for baseUrl=`src` by default in the future

### CODE REVIEW

**Comment by Josh-Cena** [comment]
> It seems that baseUrl is required for this to work, 

It seems `baseUrl` isn't required though. For example, in this PR https://github.com/facebook/docusaurus/pull/5328 I also added `"@site/*": ["./*"]`, and the import is correctly resolved without `baseUrl`. 

image

**Comment by slorber** [comment]
@Josh-Cena yes I agree with you, but unfortunately, it's not what the TS doc and my IDE say:

image

That's why I'm asking for confirmation from @orta before adding some bad config in our default config :)

**Comment by orta** [comment]
My gut says this is probably what you want, the `"include"` change would be ignored by the tsconfig resolver so I've dropped that from the PR.

**Comment by orta** [comment]
If it's wrong, then it's trivial to ship a revert

**Comment by slorber** [comment]
Thanks

Let me know when you publish :)

**Pull request merged**
