### PR TITLE
Anticipate TypeScript v5 changes

### LINKED ISSUE #148: Refactor due to "extends": [] Array support
tsconfig.json files will soon support arrays inside the `"extends"` key:
https://github.com/microsoft/TypeScript/issues/29118

I'd imagine this will simplify this project a lot, and make creating typescript configurations much more expressive.

I believe it may be best to re-imagine `tsconfig/bases` given this new TS feature. I can't imagine migrating from the non-array based setup would be hard. Existing packages would still exist as published, but wouldn't receive any new updates (do they need to be updated?).

<sub>hype train: https://twitter.com/DevinRhode2/status/1602790036050681858</sub>

### LINKED ISSUE #160: Replace all `"importsNotUsedAsValues": "error"` by `"verbatimModuleSyntax": true`
With the upcoming TS v5 release, `importsNotUsedAsValues` is being deprecated, and using it in a tsconfig file yields the following error:

```
error TS5101: Flag 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.
```

While the warning can be temporarily silenced, we'll eventually all have to drop that setting and use `verbatimModuleSyntax` instead. Do you think it would be a good idea to swap those settings now? I don't suppose this package follows semver since TS itself doesn't, so I'm guessing it shouldn't even be considered a problem to replace `importsNotUsedAsValues` with `verbatimModuleSyntax` in a new release soon?

Thanks 🙏

### PR DESCRIPTION
**Pull request by acidoxee**
Closes #148
Closes #160

### CODE REVIEW

**Comment by orta** [comment]
Yep, this is generally good - we'll need to [add the semver](https://github.com/tsconfig/bases/blob/main/bases/svelte.json#L4) marker to the bases which changed and that'd be it 👍🏻

**Comment by BPScott** [comment]
@orta it looks like two bases were modified, only one of which has an existing `_version` marker. What would you want the new `_version` values to be in these cases? It seems like this version matches the version of what the config is for (i.e. in svelte's case it is for svelte v3.x,), however the change from `importsNotUsedAsValues` to `verbatimModuleSyntax` is a change that depends on the typescript version in use not the version of the library the config is for (i.e. before and after this change svelte.json would still work with svelte 3.x). How should the version change in this case?

- `svelte.json`: Has an existing `_version` value of 3.0.0 (current published package version is (3.0.0)
- `strictest.json`: Does not currently have a `_version` value (current published package veresion is 1.0.0)

**Comment by smorimoto** [comment]
@orta What are we going to do about this? Maintainers could edit this PR, or someone could open a new PR and just take over the work.

**Comment by acidoxee** [comment]
I can modify things a bit more if needed, I'm not sure I understand what's been mentioned about versions, so if additional changes are needed I'll let you all guide me (or take over also obviously 👍)

**Comment by smorimoto** [comment]
@acidoxee Fantastic! It would be best that you complete this very nicely laid-out PR!
@orta I think all that remains is to provide the necessary guidance. Could you help us to merge this PR then make this package ready for TypeScript 5!

**Comment by orta** [comment]
Sorry been out of the office for a while, yes - any affected .json file will need version field being added and bumped to v2 (or to the next version if it already exists)

**Comment by smorimoto** [comment]
That sounds good! (I'm sorry I poked you so much. I hope your inbox isn't messed up 🤯)

**Comment by acidoxee** [comment]
Sorry for taking so long for such a small change. I've added the `_version` field to the `strictest` config, and bumped both that one's and `svelte`'s major versions. Is that what was expected?

**Review by orta — COMMENTED** [review]
Nice, this looks great to me 

@acidoxee - never apologize for contributing to OSS at your own pace. The fact that you are doing something at all is very welcome!

**Comment by smorimoto** [comment]
I totally agree with @orta! Thank you so much to everyone who helped make this happen! ❤️

**Comment by kachkaev** [comment]
I look forward to trying the new versions! `@tsconfig/strictest` still `1.0.2` as latest [on npm](https://www.npmjs.com/package/@tsconfig/strictest?activeTab=versions), which is six months old. What is left for getting v2 published?

**Comment by orta** [comment]
Deploys happen overnight

**Comment by acidoxee** [comment]
@orta seems like there was a problem with the deployment: https://github.com/tsconfig/bases/actions/runs/4522739115/jobs/7965413660

I've ran the script locally (just without the `npm publish` step), and it properly detects `svelte` and `strictest` configs should be uploaded. I'm guessing there might have been some problem with the npm registry, or with the token maybe?

**Comment by orta** [comment]
I've pushed 9f6f0fc which locks the deploy scripts stdlib and should probably fix the deploy

**Comment by smorimoto** [comment]
It's now deployed successfully and available on npm.

**Comment by kachkaev** [comment]
Should combined packages like `@tsconfig/node-lts-strictest-esm` be marked as deprecated? They will no longer be updated and are also incompatible with TS5 because of `"importsNotUsedAsValues": "error"`.

**Pull request merged**
