### PR TITLE
Exclude Node.js typings

### PR DESCRIPTION
**Pull request by retyui**
Issue #110

Before:

After:

### CODE REVIEW

**Comment by orta** [comment]
If you can get this upstreamed into the main typescript template for RN, I'm game for it - https://github.com/react-native-community/react-native-template-typescript/blob/main/template/tsconfig.json

Until then, I'd like to keep this closer to what is provided out of the box

**Comment by retyui** [comment]
@orta I've already create a PR to official template https://github.com/react-native-community/react-native-template-typescript/pull/272

**Comment by orta** [comment]
Cool, I've also bumped it to version 2 because something like this shouldn't happen in a patch release and its good to go

**Comment by orta** [comment]
Will get deployed on tomorrows scheduler

**Pull request merged**
