### PR TITLE
fix: remove "src" in create-react-app/tsconfig.json

### PR DESCRIPTION
**Pull request by aladdin-add**
it also removed "include": ["src"] in create-react-app - it's not working as expected.

### CODE REVIEW

**Comment by orta** [comment]
We probably can't do this, not all projects have "src" as their default folder I think 

I think removing the src from react example, and keeping the README the same is probably the right call

**Comment by aladdin-add** [comment]
well, revert that changes. :)

**Comment by orta** [comment]
Thanks! It will deploy overnight

**Comment by karlhorky** [comment]
I ran into this problem today - `tsconfig.json` files specified using `extends` will have `include` and `exclude` paths relative to their location, as per the [`include` docs](https://www.typescriptlang.org/tsconfig#include):

> These filenames are resolved relative to the directory containing the `tsconfig.json` file.

One way to get around it is to specify relative paths:

```json
  "include": [
    "../../../../**/.eslintrc.cjs",
    "../../../../next-env.d.ts",
    "../../../../**/*.ts",
    "../../../../**/*.tsx",
    "../../../../**/*.js",
    "../../../../**/*.jsx",
    "../../../../**/*.cjs",
    "../../../../**/*.mjs"
  ],
```

But then you're encoding your `node_modules` directory structure into the config as well... 🤔

Hm... would be great to get a `<root>` capability to add to `include` and `exclude` paths to refer to the directory with the `package.json` file, like [Jest's `<rootDir>` option](https://jestjs.io/docs/configuration#rootdir-string).

@orta I guess this doesn't exist in TS, right?

**Pull request merged**
