### PR TITLE
Fix for base Node 20 compiler lib with es2022

### PR DESCRIPTION
**Pull request by vadimsub**

### CODE REVIEW

**Comment by orta** [comment]
Fix?

**Comment by orta** [comment]
Ah, that's fine, the schemastore is out of date - es2023 is in TypeScript nowadays

**Comment by vadimsub** [comment]
> Ah, that's fine, the schemastore is out of date - es2023 is in TypeScript nowadays
so why you use it here then?

**Comment by orta** [comment]
Because it is in production TypeScript, the schemastore is a separate project which gets updates at its own pace

**Comment by vadimsub** [comment]
> Because it is in production TypeScript and accurately describes node20 support, the schemastore is a separate project which gets updates at its own pace

I meant why use this scheme if it is irrelevant?

**Comment by orta** [comment]
It's not irrelevant, its just not been updated to handle the latest TypeScript features

**Comment by vadimsub** [comment]
> Ah, that's fine, the schemastore is out of date - es2023 is in TypeScript nowadays

Dude, I'm back in touch. This situation haunts me and I looked about the release of the ES2023 release - it was not there, it is currently at the draft stage and has not yet been adopted - https://tc39.es/ecma262/. At the moment, the current version is ES2022. Please tell me where to look for information if I'm wrong.

**Comment by orta** [comment]
It comes from the files in https://github.com/microsoft/TypeScript/tree/main/src/lib

**Pull request closed without merging**
