### PR TITLE
Add lts bases

### PR DESCRIPTION
**Pull request by thematrimix**
This resolves [Issue 136](https://github.com/tsconfig/bases/issues/136) by adding a new script based on the current generate-combined to generate the lts versions. Code wise is was not a whole just go find the current LTS and use that to know what had to be extended from. Then a few tweeks were needed to deal with display and file name output.

### CODE REVIEW

**Comment by thematrimix** [comment]
One thing I did not know if I should add is the actual generated files. If so that is easy enough. Please let me know.

**Comment by orta** [comment]
I think this would probably be better if we use the [`"_version"`](https://github.com/tsconfig/bases/blob/main/bases/svelte.json#L4) to set the semver to be the same as the node version, then this is good with me 👍🏻

**Comment by thematrimix** [comment]
> I think this would probably be better if we use the [`"_version"`](https://github.com/tsconfig/bases/blob/main/bases/svelte.json#L4) to set the semver to be the same as the node version, then this is good with me 👍🏻

I have added the _version property which will map to the current node lts version minus the v aka 18.12.0. Please let me know if anything else is needed. Please note however that the whole thing is still based on the current base of that major version which at current is node18. I just want to make that explicitly clear.

**Comment by orta** [comment]
Yep, this is fine with me 👍🏻

**Pull request merged**
